# Generated by Django 3.1.4 on 2021-01-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('imageArticle', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=100)),
                ('corps_du_texte', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('echoArticle', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('auteur', models.CharField(max_length=42)),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualites.categories')),
            ],
        ),
    ]
