# Generated by Django 3.1.4 on 2021-01-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_auto_20210121_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='sous_Categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actualites.sous_categories', verbose_name='les sous categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leseditions',
            name='dateEditions',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date de l'Edition"),
        ),
    ]
