# Generated by Django 3.1.4 on 2021-01-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_sous_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imageArticle',
            field=models.ImageField(upload_to='Galeries_RMO/'),
        ),
    ]
