# Generated by Django 3.1.4 on 2021-02-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0003_auto_20210122_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_A_la_une',
            field=models.BooleanField(default=False, verbose_name='A la Une'),
        ),
    ]
