# Generated by Django 3.1.4 on 2021-02-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0004_articles_article_a_la_une'),
    ]

    operations = [
        migrations.AddField(
            model_name='aproposdenous_laradio',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actualites.categories', verbose_name='les categories'),
        ),
        migrations.AddField(
            model_name='aproposdenous_notreequipe',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actualites.categories', verbose_name='les categories'),
        ),
        migrations.AddField(
            model_name='aproposdenous_projetdavenir',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actualites.categories', verbose_name='les categories'),
        ),
        migrations.AddField(
            model_name='emissions',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actualites.categories', verbose_name='les categories'),
        ),
        migrations.AddField(
            model_name='leseditions',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actualites.categories', verbose_name='les categories'),
        ),
        migrations.AddField(
            model_name='sous_categories',
            name='Categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actualites.categories', verbose_name='les categories'),
        ),
    ]
