# Generated by Django 3.1.4 on 2021-02-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0005_auto_20210205_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AproposdeNous_NousContacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noms_contact', models.CharField(max_length=200)),
                ('objet_Message', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
