# Generated by Django 3.1.4 on 2021-02-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0006_aproposdenous_nouscontacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproposdenous_nouscontacter',
            name='mail',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='imageArticle',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
