# Generated by Django 3.1.4 on 2021-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0007_auto_20210215_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='imageArticle',
            field=models.ImageField(blank=True, null=True, upload_to='Galeries_RMO/'),
        ),
    ]
