# Generated by Django 3.1.4 on 2021-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0008_auto_20210317_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesEditions_Francaise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_francais', models.CharField(max_length=100)),
                ('dateEditions', models.DateTimeField(auto_now_add=True, verbose_name="date de l'Edition")),
                ('enregistrementJournal', models.FileField(blank=True, null=True, upload_to='jounalFrancais/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='LesEditions_Kinande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_kinande', models.CharField(max_length=100)),
                ('dateEditions', models.DateTimeField(auto_now_add=True, verbose_name="date de l'Edition")),
                ('enregistrementJournal', models.FileField(blank=True, null=True, upload_to='jounalsLangues/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='LesEditions_swahili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_swahili', models.CharField(max_length=100)),
                ('dateEditions', models.DateTimeField(auto_now_add=True, verbose_name="date de l'Edition")),
                ('enregistrementJournal', models.FileField(blank=True, null=True, upload_to='jounalswahili/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='LesEditions',
        ),
    ]
